name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  job-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Setup ruby && test
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5.1"
        run: bin/test
